version: '3.4'
services:
  tictactoe-server:
    build:
      context: .
      dockerfile: ServerDockerfile
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tictactoe
        - SPRING_DATASOURCE_USERNAME=tictac
        - SPRING_DATASOURCE_PASSWORD=tictac
    ports:
      - "8080:8080"
    depends_on:
      - db

  tictactoe-bot:
      build:
        context: .
        dockerfile: BotDockerfile
      depends_on:
        - tictactoe-server

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USER=tictac
      - POSTGRES_PASSWORD=tictac
    ports:
      - "5432:5432"