version: '3.4'
services:
  tictactoe-server:
    build: tictactoe-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  tictactoe-bot:
      build: tictactoe-bot
      depends_on:
        - tictactoe-server

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB="tictactoe"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"